version: '3.9'

services:

  rss-api-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rssdb
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin